version: "3"
x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    command: >
      sh -c " python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    <<: *default-logging

  db:
    image: postgres:alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    <<: *default-logging